### DISCUSSION TITLE
Steam Client like Theme for ProtonUp-Qt

### DISCUSSION THREAD

**Discussion by DavidoTek** [DavidoTek/ProtonUp-Qt#309] [General]
A Steam-like theme was added with PR https://github.com/DavidoTek/ProtonUp-Qt/pull/316

---

Qt allows loading custom themes from Qt Style Sheet files.

To improve the UX of ProtonUp-Qt for Steam Deck users, a Steam-like theme can be introduced to ProtonUp-Qt. See https://github.com/DavidoTek/ProtonUp-Qt/issues/55#issuecomment-1806946616.

I've implemented a basic theme loader for a Steam-like theme here: https://github.com/DavidoTek/ProtonUp-Qt/commit/2dee02f616429c6471372a1e68b1e8d006e0dcdc

---

How would a Steam-like theme look like?

![steam-colors](https://github.com/DavidoTek/ProtonUp-Qt/assets/54072917/2e3da4d6-644c-48d7-8460-7304af6a529b)

- Button Hover Background: `#464D58` + shadow

**Comment by DavidoTek** [comment]
![grafik](https://github.com/DavidoTek/ProtonUp-Qt/assets/54072917/233f2a9d-f97e-4697-bd56-96f1c66b6dcb)

---

<details>
  <summary>Steam-like Theme Code</summary>

### Color Palette definition:

```python
def PALETTE_STEAMUI():
    """ returns a Steam-ui like color palette """
    palette_steam = QPalette()
    # Needed for theming Qt's Wayland Client Side Decoration
    palette_steam.setColor(QPalette.Window, QColor(23, 29, 37))  #171D25
    palette_steam.setColor(QPalette.WindowText, Qt.white)
    return palette_steam
```
* Wayland CSD decoration theming: https://codebrowser.dev/qt5/qtwayland/src/plugins/decorations/bradient/main.cpp.html#102 

### Theme definition (`.qss`):

```css
QWidget {
    color: white;
    background-color: #171D25;
}

QPushButton {
    background-color: #282D36;
    border: none;
    border-radius: 2px;
    padding: 8px;
}

QPushButton:hover {
    background-color: #464D58;
}
```

That's less code than I thought :laughing: 

</details>

**Comment by sonic2kk** [comment]
Maybe the color for the compatibility tools list should be more like the background color for textboxes? `#282d36` I think? That way it stands out a bit more.

Also, extremely minor, but maybe we could change the font color as well to match the Steam color, which appears to be slightly more muted? It may fit these colors better :-) I'm not sure how much control we have over its color, or even things like the hover/selected color.

**Reply by DavidoTek** [reply]
> font color as well to match the Steam color

I'm not sure if it is actually some shade of gray or it just looks like that because of the font size.
I took a screen shot and the text is actually gray, but that may also be a result of the anti aliasing.

Could be something like `#EEEEEE`? Also, the font weight is a bit lower. Qt probably supports changing that, not sure if that could mess something up if the user has a custom font.

> even things like the hover/selected color.

I guess Qt style sheets work like css: https://www.w3schools.com/CSSref/tryit.php?filename=trycss_sel_link_more1

**Reply by sonic2kk** [reply]
Good point about the weight and anti aliasing. 

One very bonkers way to check that would make the text bigger and thus give more area to check, would be to set Steam's `STEAM_FORCE_DESKTOPUI_SCALING=<something large>`. This takes a decimal scale value, i.e. `2` is like setting  `200%` scale. This would make the text very big and allow for picking a potentially "more accurate" font colour, by giving more area :-)

Though, be careful, when I was testing this environment variable a few months ago, unsetting it caused Steam to forget all of my library folders and I had to manually re-add them.

**Reply by DavidoTek** [reply]
Steam seems to not be very consistent either: `#282D36` seems to be the default color for buttons. But when there are buttons which may be disabled (Settings "Storage" Tab), they are `#475261` by default and `#282D36` when disabled.
I chose `#282D36` for normal buttons and `#1D2026` for disabled buttons for now.

Also, some dialogs which have a fixed size don't like the added padding.

## `#282D36` and `#1D2026`

![grafik](https://github.com/DavidoTek/ProtonUp-Qt/assets/54072917/d2f1698a-9e01-47b2-ab0c-c95498033d55)

## `#475261` and `#282D36`

![grafik](https://github.com/DavidoTek/ProtonUp-Qt/assets/54072917/928cb1c2-8e76-43a7-84c9-98e9d6df0f34)


<details>
  <summary>newest qss code</summary>
  
```css
QWidget {
    color: #EEEEEE;
    background-color: #171D25;
    font-weight: 300;
}

QPushButton, QListWidget, QComboBox, QToolButton, QLineEdit {
    background-color: #282D36;
    border: none;
    border-radius: 2px;
    padding: 8px;
}

QListWidget::item {
    padding: 4px;
}

QPushButton:hover {
    background-color: #464D58;
}

QPushButton::pressed {
    background-color: #393F49;
}

QPushButton::disabled {
    background-color: #1D2026;
}
```
  
</details>
