### ISSUE TITLE
Cannot launch ProtonUp-QT on Steam Deck

### ISSUE THREAD

**Issue by TigerBeanst** [DavidoTek/ProtonUp-Qt#366]
**Describe the bug**  
Try to launch ProtonUp-QT but it close quickly without seeing the GUI

**To Reproduce**  
Launch it by menu or `flatpak run net.davidotek.pupgui2`

**Expected behavior**  
Normally working

**Screenshots**  
![Gif_20240317000107](https://github.com/DavidoTek/ProtonUp-Qt/assets/3889846/be586e51-58b0-4cde-abd3-24006d6ea186)

**Desktop (please complete the following information):**  
 - **Platform**: Steam Deck
 - **System**: SteamOS 3.5.17
 - **Version**: ProtonUp-Qt 2.9.0(Flatpak only has 2.9.0, not 2.9.1
 - **How did you install ProtonUp-Qt?**: Discover app store

**Additional context**  
None

**Terminal output**  
```
(deck@TigerDeck ~)$ flatpak run net.davidotek.pupgui2
F: Not sharing "/esp" with sandbox: Ignoring blocking autofs path "/esp"
/app/bin/net.davidotek.pupgui2 3:     3 δ                  תpython3 -m pupgui2 "$@"
(139)(deck@TigerDeck ~)$
```

**Comment by sonic2kk** [comment]
Cannot reproduce on my Steam Deck. Did some permissions get messed up for your Flatpak? This warning is a general Flatpak message of some kind: `F: Not sharing "/esp" with sandbox: Ignoring blocking autofs path "/esp"` - Maybe some filesystem permissions got messed up? If you have a tool like Flatseal

> Flatpak only has 2.9.0, not 2.9.1

What? I'm running ProtonUp-Qt 2.9.1 on my Steam Deck and my PC, 2.9.1 is available as a Flatpak. Although this issue is not specific to the ProtonUp-Qt version, it appears to be a Flatpak configuration issue.

**Comment by sonic2kk** [comment]
A quick Google search confirms this is a general Flatpak issue. One suggestion was to force disable Wayland and force enable X11. You can do this from the Plasma System Settings, Flatseal, or manually with a terminal command (https://github.com/streetpea/chiaki4deck/issues/112#issuecomment-1856981193).

**Comment by sonic2kk** [comment]
It would also be interesting to know if the AppImage has the same problem

**Comment by sonic2kk** [comment]
Huh, when trying to update the KDE Platforms, it fails to pull Qt6.6, saying the commit it's looking for doesn't exist. This is a different commit than the one mentioned in the chiaki4deckk issue. Perhaps some Qt6.6 update was pulled because of this breakage?

**Comment by sonic2kk** [comment]
I tried fiddling with a bunch of ProtonUp-Qt permissions in Flatseal, including access to the whole filesystem, and and while I couldn't reproduce a crash I was able to reproduce the `Not sharing /esp with sandbox` message. ProtonUp-Qt still started normally after that, however.

I noticed your terminal after that message appears to return with a 139 exit code, which iirc is a segfault inside of a container (which makes sense for a Flatpak). This could still be coming from some fault with Qt, or maybe you need to re-install the Flatpak? This might also allow you to use an up-to-date ProtonUp-Qt version, as ProtonUp-Qt 2.9.1 is definitely available.

**Comment by sonic2kk** [comment]
I'm updating to Preview (reverted back a week or so ago for testing purposes) and I'll see if the issue is present there. I should've checked but I think Beta is on 3.5.17 now.

**Comment by sonic2kk** [comment]
Updated to Preview, checked that the version is 3.5.17, ProtonUp-Qt v2.9.1 still works for me, with the most up-to-date Platforms packages from Flathub as well. So I can't reproduce this on my Steam Deck or PC. My remaining advice would be:

- Try updating to v2.9.1, if you have to please try reinstalling.
- If there are any pending KDE Platforms / Qt6.6 Platforms updates pending in Discover, please run those as well.
- Try running the command to set `--nosocket=fallback-x11` and seeing if that permission override fixes the problem for you, although I suspect not since this is possibly a segfault.
- Try resetting your Flatpak permissions, although again, possibly won't help if this is a segfault.
- See if the issue occurs on the AppImage.
- If you have a Linux PC, check if the issue also occurs there, to narrow down if this is specific to SteamOS somehow.

**Comment by TigerBeanst** [comment]
@sonic2kk 
### 1
> I'm running ProtonUp-Qt 2.9.1 on my Steam Deck and my PC, 2.9.1 is available as a Flatpak.

I install it using discover and look like there is only "shows" 2.9.0 at the website? https://flathub.org/apps/net.davidotek.pupgui2

```
(deck@TigerDeck ~)$ flatpak info --show-location net.davidotek.pupgui2
/var/lib/flatpak/app/net.davidotek.pupgui2/x86_64/stable/bd78742afc42ae3c7e947316850c15ff6599e543dc0bfd486f911c584e7f298f
```
```
(deck@TigerDeck ~)$ flatpak remote-info --log flathub net.davidotek.pupgui2
        ID: net.davidotek.pupgui2
       Ref: app/net.davidotek.pupgui2/x86_64/stable
      Arch: x86_64
    Branch: stable
Collection: org.flathub.Stable
  Download: 25.1 MB
 Installed: 96.2 MB
   Runtime: org.kde.Platform/x86_64/6.5
       Sdk: org.kde.Sdk/x86_64/6.5
    Commit: bd78742afc42ae3c7e947316850c15ff6599e543dc0bfd486f911c584e7f298f
    Parent: 90e5f68cb643946cf81baffc63fe68c08bcaab43472d8e477dbab8a55fbdc26a
   Subject: Release v2.9.1 (2e8b0a71)
      Date: 2024-01-09 22:20:17 +0000
   History:
```

Well, the commit match. (But it still shows 2.9.0 in website and Flatseal....)

### 2
> About Wayland and X11

Have been try:
```
sudo flatpak override --nosocket=fallback-x11 --socket=x11 net.davidotek.pupgui2
```
or 
disable `socket=x11`, enable `socket=Wayland`, enable `socket=fallback-x11`(I searched before) 
in Flatseal.

All doesn't work.

### 3

> I should've checked but I think Beta is on 3.5.17 now.

Nope...I am using all stable version (stable SteamOS, stable Steam client)

### 4
> Try updating to v2.9.1, if you have to please try reinstalling.

I have been trying to uninstall it and install again. It doesn't work.
